name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build-win

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: WebP-Converter-Windows
        path: |
          dist/*.exe
          dist/win-unpacked/**/*
